/// Generated by spider on 2022-08-06 17:24:45.351573

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:upnati/resources/resources.dart';

void main() {
  test('images assets test', () {
    expect(File(Images.bagImage).existsSync(), true);
    expect(File(Images.emptyAvatar).existsSync(), true);
    expect(File(Images.icEmptyBag).existsSync(), true);
    expect(File(Images.icEmptyStore).existsSync(), true);
    expect(File(Images.icRadioOff).existsSync(), true);
    expect(File(Images.icRadioOn).existsSync(), true);
    expect(File(Images.tradePointImg).existsSync(), true);
    expect(File(Images.upnatiLogo).existsSync(), true);
  });
}
