/// Generated by spider on 2022-09-25 16:44:27.161961

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:upnati/resources/resources.dart';

void main() {
  test('images assets test', () {
    expect(File(Images.aboutImg).existsSync(), true);
    expect(File(Images.appliancesImg).existsSync(), true);
    expect(File(Images.bagImage).existsSync(), true);
    expect(File(Images.bodyHealthImg).existsSync(), true);
    expect(File(Images.butterfly).existsSync(), true);
    expect(File(Images.cat).existsSync(), true);
    expect(File(Images.chico).existsSync(), true);
    expect(File(Images.clothesImg).existsSync(), true);
    expect(File(Images.cubik).existsSync(), true);
    expect(File(Images.emptyAvatar).existsSync(), true);
    expect(File(Images.emptyBoxImg).existsSync(), true);
    expect(File(Images.facebookIcon).existsSync(), true);
    expect(File(Images.fbImg).existsSync(), true);
    expect(File(Images.flowersImg).existsSync(), true);
    expect(File(Images.girlImg).existsSync(), true);
    expect(File(Images.googleIcon).existsSync(), true);
    expect(File(Images.googleImg).existsSync(), true);
    expect(File(Images.icBasketPurple).existsSync(), true);
    expect(File(Images.icBellBlue).existsSync(), true);
    expect(File(Images.icChecked).existsSync(), true);
    expect(File(Images.icContactBlue).existsSync(), true);
    expect(File(Images.icEmptyBag).existsSync(), true);
    expect(File(Images.icEmptyStore).existsSync(), true);
    expect(File(Images.icMinusAdd).existsSync(), true);
    expect(File(Images.icMoneyCard).existsSync(), true);
    expect(File(Images.icPlusAdd).existsSync(), true);
    expect(File(Images.icRadioOff).existsSync(), true);
    expect(File(Images.icRadioOn).existsSync(), true);
    expect(File(Images.icSpeaker).existsSync(), true);
    expect(File(Images.icStoreRoze).existsSync(), true);
    expect(File(Images.icUnchecked).existsSync(), true);
    expect(File(Images.icUpnatiLogoBlue).existsSync(), true);
    expect(File(Images.icecream).existsSync(), true);
    expect(File(Images.kelley).existsSync(), true);
    expect(File(Images.kitchenImg).existsSync(), true);
    expect(File(Images.logo1).existsSync(), true);
    expect(File(Images.logo2).existsSync(), true);
    expect(File(Images.logo3).existsSync(), true);
    expect(File(Images.logo4).existsSync(), true);
    expect(File(Images.minion).existsSync(), true);
    expect(File(Images.nailPolishImg).existsSync(), true);
    expect(File(Images.onlineLibraryImg).existsSync(), true);
    expect(File(Images.pacifierImg).existsSync(), true);
    expect(File(Images.packImg).existsSync(), true);
    expect(File(Images.panda).existsSync(), true);
    expect(File(Images.paymentDoneImg).existsSync(), true);
    expect(File(Images.pencilImg).existsSync(), true);
    expect(File(Images.petsImg).existsSync(), true);
    expect(File(Images.roofImg).existsSync(), true);
    expect(File(Images.share2Img).existsSync(), true);
    expect(File(Images.shareImg).existsSync(), true);
    expect(File(Images.shelfImg).existsSync(), true);
    expect(File(Images.shopImg).existsSync(), true);
    expect(File(Images.shushuLogoImg).existsSync(), true);
    expect(File(Images.termsImg).existsSync(), true);
    expect(File(Images.tradePointImg).existsSync(), true);
    expect(File(Images.upnatiBigLogo).existsSync(), true);
    expect(File(Images.upnatiLogoNew).existsSync(), true);
    expect(File(Images.upnatiMain).existsSync(), true);
    expect(File(Images.upnatiStoreLogo).existsSync(), true);
  });
}
