/// Generated by spider on 2022-09-24 00:54:33.672503

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:upnati/resources/resources.dart';

void main() {
  test('svgs assets test', () {
    expect(File(Svgs.icAdd).existsSync(), true);
    expect(File(Svgs.icAdditionalInfo).existsSync(), true);
    expect(File(Svgs.icArrowDown).existsSync(), true);
    expect(File(Svgs.icBackIcon).existsSync(), true);
    expect(File(Svgs.icBagRoze).existsSync(), true);
    expect(File(Svgs.icBasket).existsSync(), true);
    expect(File(Svgs.icBox).existsSync(), true);
    expect(File(Svgs.icBusinessEmpty).existsSync(), true);
    expect(File(Svgs.icBussinessHome).existsSync(), true);
    expect(File(Svgs.icCamera).existsSync(), true);
    expect(File(Svgs.icCategories).existsSync(), true);
    expect(File(Svgs.icCheck).existsSync(), true);
    expect(File(Svgs.icChecked).existsSync(), true);
    expect(File(Svgs.icCheckedWhite).existsSync(), true);
    expect(File(Svgs.icClose).existsSync(), true);
    expect(File(Svgs.icCloseThin).existsSync(), true);
    expect(File(Svgs.icCopy).existsSync(), true);
    expect(File(Svgs.icDeleteItem).existsSync(), true);
    expect(File(Svgs.icDropdown).existsSync(), true);
    expect(File(Svgs.icDropdownBblackArrow).existsSync(), true);
    expect(File(Svgs.icEdit).existsSync(), true);
    expect(File(Svgs.icEditGray).existsSync(), true);
    expect(File(Svgs.icEditRect).existsSync(), true);
    expect(File(Svgs.icFavoiteActive).existsSync(), true);
    expect(File(Svgs.icFavorite).existsSync(), true);
    expect(File(Svgs.icHeart).existsSync(), true);
    expect(File(Svgs.icHeartWhite).existsSync(), true);
    expect(File(Svgs.icHeeartRoze).existsSync(), true);
    expect(File(Svgs.icPhone).existsSync(), true);
    expect(File(Svgs.icPlay).existsSync(), true);
    expect(File(Svgs.icPlus).existsSync(), true);
    expect(File(Svgs.icPlusCircle).existsSync(), true);
    expect(File(Svgs.icProfile).existsSync(), true);
    expect(File(Svgs.icProfileRoze).existsSync(), true);
    expect(File(Svgs.icRedHeart).existsSync(), true);
    expect(File(Svgs.icRing).existsSync(), true);
    expect(File(Svgs.icSearch).existsSync(), true);
    expect(File(Svgs.icShare).existsSync(), true);
    expect(File(Svgs.icShareSmall).existsSync(), true);
    expect(File(Svgs.icStar).existsSync(), true);
    expect(File(Svgs.icStarEmpty).existsSync(), true);
    expect(File(Svgs.icStarMarked).existsSync(), true);
    expect(File(Svgs.icStarNotmarked).existsSync(), true);
    expect(File(Svgs.icStarYellowMarked).existsSync(), true);
    expect(File(Svgs.icStarYellowUnmarked).existsSync(), true);
    expect(File(Svgs.icStore).existsSync(), true);
    expect(File(Svgs.icTrash).existsSync(), true);
    expect(File(Svgs.icUnchecked).existsSync(), true);
    expect(File(Svgs.icUserEmpty).existsSync(), true);
    expect(File(Svgs.icVideo).existsSync(), true);
    expect(File(Svgs.icWhiteSmallArrow).existsSync(), true);
  });
}
