/// Generated by spider on 2022-08-10 03:44:41.730303

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:upnati/resources/resources.dart';

void main() {
  test('svgs assets test', () {
    expect(File(Svgs.icAdd).existsSync(), true);
    expect(File(Svgs.icBackIcon).existsSync(), true);
    expect(File(Svgs.icCamera).existsSync(), true);
    expect(File(Svgs.icCategories).existsSync(), true);
    expect(File(Svgs.icCheck).existsSync(), true);
    expect(File(Svgs.icChecked).existsSync(), true);
    expect(File(Svgs.icClose).existsSync(), true);
    expect(File(Svgs.icCopy).existsSync(), true);
    expect(File(Svgs.icDropdown).existsSync(), true);
    expect(File(Svgs.icEdit).existsSync(), true);
    expect(File(Svgs.icEditRect).existsSync(), true);
    expect(File(Svgs.icFavoiteActive).existsSync(), true);
    expect(File(Svgs.icFavorite).existsSync(), true);
    expect(File(Svgs.icPhone).existsSync(), true);
    expect(File(Svgs.icPlus).existsSync(), true);
    expect(File(Svgs.icProfile).existsSync(), true);
    expect(File(Svgs.icRing).existsSync(), true);
    expect(File(Svgs.icSearch).existsSync(), true);
    expect(File(Svgs.icShare).existsSync(), true);
    expect(File(Svgs.icStar).existsSync(), true);
    expect(File(Svgs.icStarEmpty).existsSync(), true);
    expect(File(Svgs.icStore).existsSync(), true);
    expect(File(Svgs.icTrash).existsSync(), true);
    expect(File(Svgs.icUnchecked).existsSync(), true);
    expect(File(Svgs.icVideo).existsSync(), true);
  });
}
