name: upnati
description: Upnati internet reseller.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^5.0.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.3
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.10.0
  injectable: ^1.5.3
  get_it: ^7.2.0
  logger: ^1.1.0
  webview_flutter: ^3.0.4
  easy_localization: ^3.0.1
  flutter_hooks: ^0.18.5+1
  flutter_form_builder: ^7.5.0
  auto_route: ^5.0.1
  retrofit: ^3.3.1
  dio: ^4.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_inset_box_shadow: ^1.0.8
  pin_code_fields: ^7.4.0
  tab_indicator_styler: ^2.0.0
  form_builder_validators: ^8.3.0
  flutter_masked_text2: ^0.9.1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  infinite_scroll_pagination: ^3.2.0
  carousel_slider: ^4.1.1
  flutter_image_compress: ^1.1.3
  video_thumbnail: ^0.5.3
  video_player: ^2.4.7
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  retrofit_generator: ^4.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.3
  auto_route_generator: ^5.0.2
  dart_code_metrics: ^4.17.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/svgs/
    - assets/fonts/
    - assets/langs/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeui.ttf

