// Generated by spider on 2022-09-25 16:44:26.970876

part of 'resources.dart';

class Images {
  Images._();

  static const String aboutImg = 'assets/imgs/about_img.png';
  static const String appliancesImg = 'assets/imgs/appliances_img.png';
  static const String bagImage = 'assets/imgs/bag_image.png';
  static const String bodyHealthImg = 'assets/imgs/body_health_img.png';
  static const String butterfly = 'assets/imgs/butterfly.png';
  static const String cat = 'assets/imgs/cat.png';
  static const String chico = 'assets/imgs/chico.png';
  static const String clothesImg = 'assets/imgs/clothes_img.png';
  static const String cubik = 'assets/imgs/cubik.png';
  static const String emptyAvatar = 'assets/imgs/empty_avatar.png';
  static const String emptyBoxImg = 'assets/imgs/empty_box_img.png';
  static const String facebookIcon = 'assets/imgs/facebook_icon.png';
  static const String fbImg = 'assets/imgs/fb_img.png';
  static const String flowersImg = 'assets/imgs/flowers_img.png';
  static const String girlImg = 'assets/imgs/girl_img.png';
  static const String googleIcon = 'assets/imgs/google_icon.png';
  static const String googleImg = 'assets/imgs/google_img.png';
  static const String icBasketPurple = 'assets/imgs/ic_basket_purple.png';
  static const String icBellBlue = 'assets/imgs/ic_bell_blue.png';
  static const String icChecked = 'assets/imgs/ic_checked.png';
  static const String icContactBlue = 'assets/imgs/ic_contact_blue.png';
  static const String icEmptyBag = 'assets/imgs/ic_empty_bag.png';
  static const String icEmptyStore = 'assets/imgs/ic_empty_store.png';
  static const String icMinusAdd = 'assets/imgs/ic_minus_add.png';
  static const String icMoneyCard = 'assets/imgs/ic_money_card.png';
  static const String icPlusAdd = 'assets/imgs/ic_plus_add.png';
  static const String icRadioOff = 'assets/imgs/ic_radio_off.png';
  static const String icRadioOn = 'assets/imgs/ic_radio_on.png';
  static const String icSpeaker = 'assets/imgs/ic_speaker.png';
  static const String icStoreRoze = 'assets/imgs/ic_store_roze.png';
  static const String icUnchecked = 'assets/imgs/ic_unchecked.png';
  static const String icUpnatiLogoBlue = 'assets/imgs/ic_upnati_logo_blue.png';
  static const String icecream = 'assets/imgs/icecream.png';
  static const String kelley = 'assets/imgs/kelley.png';
  static const String kitchenImg = 'assets/imgs/kitchen_img.png';
  static const String logo1 = 'assets/imgs/logo1.png';
  static const String logo2 = 'assets/imgs/logo2.png';
  static const String logo3 = 'assets/imgs/logo3.png';
  static const String logo4 = 'assets/imgs/logo4.png';
  static const String minion = 'assets/imgs/minion.png';
  static const String nailPolishImg = 'assets/imgs/nail_polish_img.png';
  static const String onlineLibraryImg = 'assets/imgs/online_library_img.png';
  static const String pacifierImg = 'assets/imgs/pacifier_img.png';
  static const String packImg = 'assets/imgs/pack_img.png';
  static const String panda = 'assets/imgs/panda.png';
  static const String paymentDoneImg = 'assets/imgs/payment_done_img.png';
  static const String pencilImg = 'assets/imgs/pencil_img.png';
  static const String petsImg = 'assets/imgs/pets_img.png';
  static const String roofImg = 'assets/imgs/roof_img.png';
  static const String share2Img = 'assets/imgs/share2_img.png';
  static const String shareImg = 'assets/imgs/share_img.png';
  static const String shelfImg = 'assets/imgs/shelf_img.png';
  static const String shopImg = 'assets/imgs/shop_img.png';
  static const String shushuLogoImg = 'assets/imgs/shushu_logo_img.png';
  static const String termsImg = 'assets/imgs/terms_img.png';
  static const String tradePointImg = 'assets/imgs/trade_point_img.png';
  static const String upnatiBigLogo = 'assets/imgs/upnati_big_logo.png';
  static const String upnatiLogoNew = 'assets/imgs/upnati_logo_new.png';
  static const String upnatiMain = 'assets/imgs/upnati_main.png';
  static const String upnatiStoreLogo = 'assets/imgs/upnati_store_logo.png';
}
