// Generated by spider on 2022-08-10 03:44:41.319374

part of 'resources.dart';

class Images {
  Images._();

  static const String bagImage = 'assets/imgs/bag_image.png';
  static const String emptyAvatar = 'assets/imgs/empty_avatar.png';
  static const String facebookIcon = 'assets/imgs/facebook_icon.png';
  static const String googleIcon = 'assets/imgs/google_icon.png';
  static const String icEmptyBag = 'assets/imgs/ic_empty_bag.png';
  static const String icEmptyStore = 'assets/imgs/ic_empty_store.png';
  static const String icRadioOff = 'assets/imgs/ic_radio_off.png';
  static const String icRadioOn = 'assets/imgs/ic_radio_on.png';
  static const String tradePointImg = 'assets/imgs/trade_point_img.png';
  static const String upnatiLogo = 'assets/imgs/upnati_logo.png';
}
