// Generated by spider on 2022-08-27 21:02:46.556393

part of 'resources.dart';

class Images {
  Images._();

  static const String bagImage = 'assets/imgs/bag_image.png';
  static const String butterfly = 'assets/imgs/butterfly.png';
  static const String cat = 'assets/imgs/cat.png';
  static const String chico = 'assets/imgs/chico.png';
  static const String cubik = 'assets/imgs/cubik.png';
  static const String emptyAvatar = 'assets/imgs/empty_avatar.png';
  static const String facebookIcon = 'assets/imgs/facebook_icon.png';
  static const String flowersImg = 'assets/imgs/flowers_img.png';
  static const String googleIcon = 'assets/imgs/google_icon.png';
  static const String icChecked = 'assets/imgs/ic_checked.png';
  static const String icEmptyBag = 'assets/imgs/ic_empty_bag.png';
  static const String icEmptyStore = 'assets/imgs/ic_empty_store.png';
  static const String icRadioOff = 'assets/imgs/ic_radio_off.png';
  static const String icRadioOn = 'assets/imgs/ic_radio_on.png';
  static const String icUnchecked = 'assets/imgs/ic_unchecked.png';
  static const String icUpnatiLogoBlue = 'assets/imgs/ic_upnati_logo_blue.png';
  static const String icecream = 'assets/imgs/icecream.png';
  static const String kelley = 'assets/imgs/kelley.png';
  static const String minion = 'assets/imgs/minion.png';
  static const String panda = 'assets/imgs/panda.png';
  static const String shelfImg = 'assets/imgs/shelf_img.png';
  static const String shushuLogoImg = 'assets/imgs/shushu_logo_img.png';
  static const String tradePointImg = 'assets/imgs/trade_point_img.png';
  static const String upnatiLogo = 'assets/imgs/upnati_logo.png';
}
