// Generated by spider on 2022-08-10 03:44:41.724847

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String icAdd = 'assets/svgs/ic_add.svg';
  static const String icBackIcon = 'assets/svgs/ic_back_icon.svg';
  static const String icCamera = 'assets/svgs/ic_camera.svg';
  static const String icCategories = 'assets/svgs/ic_categories.svg';
  static const String icCheck = 'assets/svgs/ic_check.svg';
  static const String icChecked = 'assets/svgs/ic_checked.svg';
  static const String icClose = 'assets/svgs/ic_close.svg';
  static const String icCopy = 'assets/svgs/ic_copy.svg';
  static const String icDropdown = 'assets/svgs/ic_dropdown.svg';
  static const String icEdit = 'assets/svgs/ic_edit.svg';
  static const String icEditRect = 'assets/svgs/ic_edit_rect.svg';
  static const String icFavoiteActive = 'assets/svgs/ic_favoite_active.svg';
  static const String icFavorite = 'assets/svgs/ic_favorite.svg';
  static const String icPhone = 'assets/svgs/ic_phone.svg';
  static const String icPlus = 'assets/svgs/ic_plus.svg';
  static const String icProfile = 'assets/svgs/ic_profile.svg';
  static const String icRing = 'assets/svgs/ic_ring.svg';
  static const String icSearch = 'assets/svgs/ic_search.svg';
  static const String icShare = 'assets/svgs/ic_share.svg';
  static const String icStar = 'assets/svgs/ic_star.svg';
  static const String icStarEmpty = 'assets/svgs/ic_star_empty.svg';
  static const String icStore = 'assets/svgs/ic_store.svg';
  static const String icTrash = 'assets/svgs/ic_trash.svg';
  static const String icUnchecked = 'assets/svgs/ic_unchecked.svg';
  static const String icVideo = 'assets/svgs/ic_video.svg';
}
