// Generated by spider on 2022-09-25 16:44:27.342144

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String icAdd = 'assets/svgs/ic_add.svg';
  static const String icAdditionalInfo = 'assets/svgs/ic_additional_info.svg';
  static const String icArrowDown = 'assets/svgs/ic_arrow_down.svg';
  static const String icBackIcon = 'assets/svgs/ic_back_icon.svg';
  static const String icBagRoze = 'assets/svgs/ic_bag_roze.svg';
  static const String icBasket = 'assets/svgs/ic_basket.svg';
  static const String icBox = 'assets/svgs/ic_box.svg';
  static const String icBusinessEmpty = 'assets/svgs/ic_business_empty.svg';
  static const String icBussinessHome = 'assets/svgs/ic_bussiness_home.svg';
  static const String icCamera = 'assets/svgs/ic_camera.svg';
  static const String icCategories = 'assets/svgs/ic_categories.svg';
  static const String icCheck = 'assets/svgs/ic_check.svg';
  static const String icChecked = 'assets/svgs/ic_checked.svg';
  static const String icCheckedWhite = 'assets/svgs/ic_checked_white.svg';
  static const String icClose = 'assets/svgs/ic_close.svg';
  static const String icCloseThin = 'assets/svgs/ic_close_thin.svg';
  static const String icCopy = 'assets/svgs/ic_copy.svg';
  static const String icDeleteItem = 'assets/svgs/ic_delete_item.svg';
  static const String icDropdown = 'assets/svgs/ic_dropdown.svg';
  static const String icDropdownBblackArrow =
      'assets/svgs/ic_dropdown_bblack_arrow.svg';
  static const String icEdit = 'assets/svgs/ic_edit.svg';
  static const String icEditGray = 'assets/svgs/ic_edit_gray.svg';
  static const String icEditRect = 'assets/svgs/ic_edit_rect.svg';
  static const String icFavoiteActive = 'assets/svgs/ic_favoite_active.svg';
  static const String icFavorite = 'assets/svgs/ic_favorite.svg';
  static const String icHeart = 'assets/svgs/ic_heart.svg';
  static const String icHeartWhite = 'assets/svgs/ic_heart_white.svg';
  static const String icHeeartRoze = 'assets/svgs/ic_heeart_roze.svg';
  static const String icPhone = 'assets/svgs/ic_phone.svg';
  static const String icPlay = 'assets/svgs/ic_play.svg';
  static const String icPlus = 'assets/svgs/ic_plus.svg';
  static const String icPlusCircle = 'assets/svgs/ic_plus_circle.svg';
  static const String icPlusRounded = 'assets/svgs/ic_plus_rounded.svg';
  static const String icProfile = 'assets/svgs/ic_profile.svg';
  static const String icProfileRoze = 'assets/svgs/ic_profile_roze.svg';
  static const String icRedHeart = 'assets/svgs/ic_red_heart.svg';
  static const String icRing = 'assets/svgs/ic_ring.svg';
  static const String icSearch = 'assets/svgs/ic_search.svg';
  static const String icShare = 'assets/svgs/ic_share.svg';
  static const String icShareSmall = 'assets/svgs/ic_share_small.svg';
  static const String icStar = 'assets/svgs/ic_star.svg';
  static const String icStarEmpty = 'assets/svgs/ic_star_empty.svg';
  static const String icStarMarked = 'assets/svgs/ic_star_marked.svg';
  static const String icStarNotmarked = 'assets/svgs/ic_star_notmarked.svg';
  static const String icStarYellowMarked =
      'assets/svgs/ic_star_yellow_marked.svg';
  static const String icStarYellowUnmarked =
      'assets/svgs/ic_star_yellow_unmarked.svg';
  static const String icStore = 'assets/svgs/ic_store.svg';
  static const String icTrash = 'assets/svgs/ic_trash.svg';
  static const String icUnchecked = 'assets/svgs/ic_unchecked.svg';
  static const String icUserEmpty = 'assets/svgs/ic_user_empty.svg';
  static const String icVideo = 'assets/svgs/ic_video.svg';
  static const String icWhiteSmallArrow =
      'assets/svgs/ic_white_small_arrow.svg';
}
